/**
 * V0 pure reducer for the A2UI renderer.
 *
 * Handles all 12 spec verbs + the internal `clearPendingUndo` action.
 * PURE function: no Date.now(), no Math.random(), no I/O, no side effects.
 * Side effects (haptics, toasts, AI calls, navigation primitive calls) live in
 * middleware that wraps this reducer.
 *
 * Immutability contract:
 *   Every state mutation produces new Map/array instances. Never calls
 *   state.slots.set(...) or state.collections.get(...).rowOrder.push(...).
 *   This is verified by T-0006-012a (Object.freeze before dispatch).
 *
 * Unknown collection graceful degradation:
 *   If a collection action references a collectionId not in state, the reducer
 *   returns state unchanged. The cross-ref validator (validateCrossRefs in
 *   @app-creator/protocol) should have caught this upstream. The renderer
 *   routes the warning through host.onUnknownNodeType — but that is middleware's
 *   job; the reducer just no-ops.
 */
import type {RendererState, RendererAction, CollectionState, Row, RowId} from './types.js'
import {MAX_ROWS} from './types.js'

// MAX_ROWS re-exported so reducer.test.ts can import it
export {MAX_ROWS} from './types.js'

// -- ID generation ------------------------------------------------------------
// The reducer is pure, so row IDs cannot come from Math.random() or Date.now().
// IDs are generated by a tiny counter seeded from the call count so that
// tests get deterministic IDs. In production the counter produces unique IDs
// across the session lifetime.
//
// IMPORTANT: this counter is module-level state. It is reset in tests via
// resetRowIdCounter(). Production code never calls resetRowIdCounter().
let _rowIdCounter = 0

export function resetRowIdCounter(): void {
  _rowIdCounter = 0
}

export function generateRowId(): RowId {
  _rowIdCounter += 1
  return `row_${_rowIdCounter}`
}

// -- Reducer ------------------------------------------------------------------

export function reducer(state: RendererState, action: RendererAction): RendererState {
  switch (action.type) {
    // -------------------------------------------------------------------------
    // 1. set — write a BindingValue to a named state slot
    // -------------------------------------------------------------------------
    case 'set': {
      return {
        ...state,
        slots: new Map(state.slots).set(action.target, action.value),
      }
    }

    // -------------------------------------------------------------------------
    // 2. update — patch named fields on a collection item by itemId
    // -------------------------------------------------------------------------
    case 'update': {
      const collection = state.collections.get(action.collection)
      if (!collection) return state
      const existingRow = collection.rows.get(action.itemId)
      if (!existingRow) return state
      const patchedRow: Row = {...existingRow, ...action.patch}
      const newRows = new Map(collection.rows).set(action.itemId, patchedRow)
      return {
        ...state,
        collections: new Map(state.collections).set(action.collection, {
          ...collection,
          rows: newRows,
        }),
      }
    }

    // -------------------------------------------------------------------------
    // 3. reset — clear a state slot back to its Spec.initialState value
    // -------------------------------------------------------------------------
    case 'reset': {
      const initialValue = state.spec.initialState?.[action.target]
      if (initialValue === undefined) {
        // Slot not in initialState — remove it (revert to absent)
        const newSlots = new Map(state.slots)
        newSlots.delete(action.target)
        return {...state, slots: newSlots}
      }
      return {
        ...state,
        slots: new Map(state.slots).set(action.target, initialValue),
      }
    }

    // -------------------------------------------------------------------------
    // 4. addItem — append a new row to a collection
    // Undo branch: if pendingUndo matches this collection + rowId, restore at
    // original insertIndex instead of appending. This is the undo restore path.
    // -------------------------------------------------------------------------
    case 'addItem': {
      const collection = state.collections.get(action.collection)
      if (!collection) return state

      // Check if this addItem is an undo-restore dispatch from undoBuffer middleware.
      // The undoBuffer middleware passes the original rowId via a synthetic addItem
      // that carries __restoreRowId — but the Action type is strict, so we detect
      // the undo case via pendingUndo state matching the collection.
      // The undoBuffer middleware sets pendingUndo and then dispatches addItem with
      // the original row data; the row id to restore is in pendingUndo.rowId.
      const isUndoRestore =
        state.pendingUndo !== null &&
        state.pendingUndo.collectionId === action.collection

      if (isUndoRestore && state.pendingUndo !== null) {
        const {rowId, rowData, insertIndex} = state.pendingUndo
        const newRows = new Map(collection.rows).set(rowId, rowData)
        // Splice back at original position
        const newOrder = [...collection.rowOrder]
        const clampedIndex = Math.min(insertIndex, newOrder.length)
        newOrder.splice(clampedIndex, 0, rowId)
        return {
          ...state,
          pendingUndo: null,
          collections: new Map(state.collections).set(action.collection, {
            ...collection,
            rows: newRows,
            rowOrder: newOrder,
          }),
        }
      }

      // Normal addItem: enforce MAX_ROWS limit
      if (collection.rowOrder.length >= MAX_ROWS) {
        // T-0006-010: 51st add no-ops. Warning is emitted by undoBuffer/middleware
        // layer — reducer is side-effect-free.
        return state
      }

      const newId = generateRowId()
      // Resolve state-binding references in item values against current slots.
      // `{kind:'state', slot}` becomes the live slot value; literals pass through.
      const resolvedItem: Row = {}
      for (const [key, raw] of Object.entries(action.item)) {
        if (
          raw !== null &&
          typeof raw === 'object' &&
          'kind' in raw &&
          (raw as {kind: string}).kind === 'state'
        ) {
          const slot = (raw as {slot: string}).slot
          const slotValue = state.slots.get(slot)
          resolvedItem[key] = (slotValue ?? '') as Row[string]
        } else {
          resolvedItem[key] = raw as Row[string]
        }
      }
      const newRows = new Map(collection.rows).set(newId, resolvedItem)
      const newOrder = [...collection.rowOrder, newId]
      return {
        ...state,
        collections: new Map(state.collections).set(action.collection, {
          ...collection,
          rows: newRows,
          rowOrder: newOrder,
        }),
      }
    }

    // -------------------------------------------------------------------------
    // 5. removeItem — delete a row from a collection by itemId
    // Also sets pendingUndo with the row's data + original index.
    // The removedAt timestamp is set by the middleware (Date.now()) and passed
    // via the pendingUndo that the middleware writes. But since the reducer is
    // pure, we set removedAt to 0 as a sentinel — the middleware layer updates
    // it after the reducer runs by re-writing state.pendingUndo.removedAt.
    // Actually: we allow the reducer to set removedAt = 0 here; the undoBuffer
    // middleware sets the real timestamp after dispatch via a second INTERNAL
    // state update. That second update is the clearPendingUndo replacement that
    // sets the real removedAt. This is the correct pure approach.
    //
    // Simpler: we accept removedAt from the middleware as part of the action.
    // But Action is strict — no extra fields allowed. So we use a convention:
    // removedAt is always set to 0 in the reducer; the undoBuffer middleware
    // re-sets it via a separate internal action. In practice, the 5s timer
    // starts when undoBuffer intercepts removeItem, not when the reducer runs,
    // so the timing source is correct.
    // -------------------------------------------------------------------------
    case 'removeItem': {
      const collection = state.collections.get(action.collection)
      if (!collection) return state
      const existingRow = collection.rows.get(action.itemId)
      if (!existingRow) return state

      const insertIndex = collection.rowOrder.indexOf(action.itemId)
      const newRows = new Map(collection.rows)
      newRows.delete(action.itemId)
      const newOrder = collection.rowOrder.filter(id => id !== action.itemId)

      return {
        ...state,
        pendingUndo: {
          collectionId: action.collection,
          rowId: action.itemId,
          rowData: existingRow,
          insertIndex: insertIndex >= 0 ? insertIndex : 0,
          // removedAt is set to 0 here; undoBuffer middleware sets the real
          // timestamp via its own closure — it knows when it intercepted the action.
          removedAt: 0,
        },
        collections: new Map(state.collections).set(action.collection, {
          ...collection,
          rows: newRows,
          rowOrder: newOrder,
        }),
      }
    }

    // -------------------------------------------------------------------------
    // 6. updateItem — patch fields on a specific collection row
    // -------------------------------------------------------------------------
    case 'updateItem': {
      const collection = state.collections.get(action.collection)
      if (!collection) return state
      const existingRow = collection.rows.get(action.itemId)
      if (!existingRow) return state  // T-0006-009: unknown itemId no-ops
      const patchedRow: Row = {...existingRow, ...action.patch}
      const newRows = new Map(collection.rows).set(action.itemId, patchedRow)
      return {
        ...state,
        collections: new Map(state.collections).set(action.collection, {
          ...collection,
          rows: newRows,
        }),
      }
    }

    // -------------------------------------------------------------------------
    // 7. clearCollection — reset rows to seed data (not empty)
    // T-0006-011: clearCollection resets to seed data, not empty.
    // -------------------------------------------------------------------------
    case 'clearCollection': {
      const collection = state.collections.get(action.collection)
      if (!collection) return state
      const {rows: seedRows, rowOrder: seedOrder} = buildCollectionFromSeedData(collection.schema)
      return {
        ...state,
        collections: new Map(state.collections).set(action.collection, {
          ...collection,
          rows: seedRows,
          rowOrder: seedOrder,
        }),
      }
    }

    // -------------------------------------------------------------------------
    // 8. navigate — push screen onto history stack, update currentScreenId
    // -------------------------------------------------------------------------
    case 'navigate': {
      return {
        ...state,
        currentScreenId: action.target,
        history: [...state.history, state.currentScreenId],
      }
    }

    // -------------------------------------------------------------------------
    // 9. back — pop the history stack
    // -------------------------------------------------------------------------
    case 'back': {
      if (state.history.length === 0) {
        // Empty history — no-op at reducer level. Navigation middleware
        // routes this through host.onNavigationError('back-on-empty-history').
        return state
      }
      const newHistory = [...state.history]
      const previousScreenId = newHistory.pop() as string
      return {
        ...state,
        currentScreenId: previousScreenId,
        history: newHistory,
      }
    }

    // -------------------------------------------------------------------------
    // 10. capture — no-op at reducer (image picker side-effect lives in middleware)
    // -------------------------------------------------------------------------
    case 'capture': {
      return state
    }

    // -------------------------------------------------------------------------
    // 11. toast — no-op at reducer (toast side-effect lives in toast middleware)
    // -------------------------------------------------------------------------
    case 'toast': {
      return state
    }

    // -------------------------------------------------------------------------
    // 12. aiProcess — no-op at reducer (AI dispatch side-effect in aiBridge middleware)
    // -------------------------------------------------------------------------
    case 'aiProcess': {
      return state
    }

    // -------------------------------------------------------------------------
    // Internal: clearPendingUndo — dispatched by undoBuffer middleware on 5s expiry
    // -------------------------------------------------------------------------
    case 'clearPendingUndo': {
      return {...state, pendingUndo: null}
    }

    // -------------------------------------------------------------------------
    // Internal: __RESET__ — dispatched by useRendererState on spec-ref change.
    // Rebuilds all state from the new spec (slots, collections, screenId, history).
    // -------------------------------------------------------------------------
    case '__RESET__': {
      return buildInitialRendererState(action.spec)
    }

    // -------------------------------------------------------------------------
    // Defensive default — unknown action types (e.g., forward-compat)
    // -------------------------------------------------------------------------
    default: {
      // TypeScript exhaustiveness: this branch catches actions that slip through
      // if new verbs are added to RendererAction before the switch is updated.
      return state
    }
  }
}

// -- Helpers ------------------------------------------------------------------

/**
 * buildCollectionFromSeedData — converts a Collection's seedData array into
 * the runtime (rows: Map, rowOrder: RowId[]) representation.
 * Used both at initialization (useRendererState) and by clearCollection.
 */
export function buildCollectionFromSeedData(schema: import('@app-creator/protocol').Collection): {
  rows: Map<RowId, Row>
  rowOrder: RowId[]
} {
  const rows = new Map<RowId, Row>()
  const rowOrder: RowId[] = []
  for (const seedRow of schema.seedData) {
    const id = generateRowId()
    rows.set(id, seedRow as Row)
    rowOrder.push(id)
  }
  return {rows, rowOrder}
}

/**
 * buildInitialRendererState — constructs the initial RendererState from a Spec.
 * Exported for use by useRendererState and tests.
 */
export function buildInitialRendererState(spec: import('@app-creator/protocol').Spec): RendererState {
  const slots = new Map<string, import('@app-creator/protocol').BindingValue>(
    Object.entries(spec.initialState ?? {}),
  )

  const collections = new Map<string, CollectionState>()
  for (const collection of spec.collections ?? []) {
    const {rows, rowOrder} = buildCollectionFromSeedData(collection)
    collections.set(collection.id, {schema: collection, rows, rowOrder})
  }

  return {
    spec,
    slots,
    collections,
    currentScreenId: spec.initialScreenId,
    history: [],
    pendingUndo: null,
  }
}

// -- RESET action (internal to useRendererState) -----------------------------
// The spec-ref change reset is handled by useRendererState using the "derived
// state from props" pattern (same as M1 legacy/state/useA2UIState.ts:112-113).
// The reducer handles it via buildInitialRendererState called from useRendererState.
