/**
 * gen-types.ts — Generates packages/protocol/generated/types.ts
 *
 * Exports inferred TypeScript types for the V0 protocol. Non-recursive types
 * use z.infer<> aliases; the recursive Node type is hand-declared (z.infer
 * cannot resolve recursive references — ADR-0005 §E / F-7).
 *
 * Hand-rolled rather than using zod-to-ts — that package adds a runtime dep
 * for marginal value, and the type shapes are stable enough to maintain here.
 *
 * Ordering: closed enums first (alphabetical), then structural types.
 *
 * Run via: pnpm --filter @app-creator/protocol codegen
 */
import * as fs from 'node:fs'
import * as path from 'node:path'
import {fileURLToPath} from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..')
const OUTPUT_PATH = path.join(REPO_ROOT, 'packages', 'protocol', 'generated', 'types.ts')

// NOTE: This file is generated. Do not hand-edit — edit the Zod source and
// re-run `pnpm --filter @app-creator/protocol codegen`.
const HEADER = `/**
 * types.ts — Generated TypeScript types for the V0 protocol.
 *
 * DO NOT EDIT. Source of truth: packages/protocol/src/
 * Re-generate: pnpm --filter @app-creator/protocol codegen
 *
 * Generated by scripts/gen-types.ts
 */
`

// Closed enum types — alphabetical order for determinism.
// Values are inlined verbatim from the Zod schema enums.
const ENUM_TYPES = `
// ---------------------------------------------------------------------------
// § Closed enum types (alphabetical)
// ---------------------------------------------------------------------------

export type Archetype = 'ListCRUD' | 'Tracker' | 'Journal' | 'Calculator' | 'unknown'

export type BindingKind = 'literal' | 'state' | 'collectionField'

export type ColorToken =
  | 'bg'
  | 'bg-elevated'
  | 'bg-overlay'
  | 'fg'
  | 'fg-muted'
  | 'fg-faint'
  | 'divider'
  | 'accent'
  | 'accent-fg'
  | 'success'
  | 'warning'
  | 'danger'

export type Elevation = 'elevation-flat' | 'elevation-raised' | 'elevation-floating'

export type MotionCurve = 'motion-instant' | 'motion-snappy' | 'motion-smooth' | 'motion-springy'

export type NavPattern = 'none' | 'stack' | 'tabs' | 'modal-overlay'

export type Palette = 'focus' | 'health' | 'money' | 'social' | 'learn' | 'play'

export type RadiusToken = 'radius-none' | 'radius-sm' | 'radius-md' | 'radius-lg' | 'radius-full'

export type SlotKind = 'none' | 'icon' | 'avatar' | 'badge'

export type SpaceToken =
  | 'space-none'
  | 'space-xs'
  | 'space-sm'
  | 'space-md'
  | 'space-lg'
  | 'space-xl'

export type Stance = 'productive' | 'expressive'

export type Tone = 'success' | 'warning' | 'danger'

export type TypeRole =
  | 'type-display'
  | 'type-h1'
  | 'type-h2'
  | 'type-body'
  | 'type-caption'
  | 'type-micro'
`

// Binding types
const BINDING_TYPES = `
// ---------------------------------------------------------------------------
// § Binding types
// ---------------------------------------------------------------------------

export type StringBinding =
  | {kind: 'literal'; value: string}
  | {kind: 'state'; slot: string}
  | {kind: 'collectionField'; collectionId: string; field: string}

export type NumberBinding =
  | {kind: 'literal'; value: number}
  | {kind: 'state'; slot: string}
  | {kind: 'collectionField'; collectionId: string; field: string}

export type BooleanBinding =
  | {kind: 'literal'; value: boolean}
  | {kind: 'state'; slot: string}
  | {kind: 'collectionField'; collectionId: string; field: string}

export type DateBinding =
  | {kind: 'literal'; value: string}
  | {kind: 'state'; slot: string}
  | {kind: 'collectionField'; collectionId: string; field: string}

export type ImageBinding =
  | {kind: 'literal'; value: string}
  | {kind: 'state'; slot: string}
  | {kind: 'collectionField'; collectionId: string; field: string}

export type BindingValue = string | number | boolean
`

// Action types — 12 verbs, 'share' absent (F-4 cut).
const ACTION_TYPES = `
// ---------------------------------------------------------------------------
// § Action types (12 verbs — 'share' cut per F-4)
// ---------------------------------------------------------------------------

export type Action =
  | {type: 'set'; target: string; value: BindingValue}
  | {type: 'update'; collection: string; itemId: string; patch: Record<string, BindingValue>}
  | {type: 'reset'; target: string}
  | {type: 'addItem'; collection: string; item: Record<string, BindingValue>}
  | {type: 'removeItem'; collection: string; itemId: string}
  | {type: 'updateItem'; collection: string; itemId: string; patch: Record<string, BindingValue>}
  | {type: 'clearCollection'; collection: string; confirmText?: string}
  | {type: 'navigate'; target: string}
  | {type: 'back'}
  | {type: 'capture'; target: string}
  | {type: 'toast'; message: string; tone?: Tone}
  | {type: 'aiProcess'; task: 'summarize'; collection: string; prompt: string; target: string}
`

// Collection types
const COLLECTION_TYPES = `
// ---------------------------------------------------------------------------
// § Collection types
// ---------------------------------------------------------------------------

export type FieldType =
  | {type: 'string'}
  | {type: 'number'}
  | {type: 'boolean'}
  | {type: 'date'}
  | {type: 'image'}
  | {type: 'reference'; targetCollectionId: string}

export type CollectionField = {
  name: string
  type: FieldType
  required?: boolean
}

export type Collection = {
  id: string
  name: string
  fields: CollectionField[]
  seedData: Record<string, BindingValue>[]
  syncMode: 'local' | 'cloud-private'
}
`

// Slot types
const SLOT_TYPES = `
// ---------------------------------------------------------------------------
// § Slot types (ListItem leading/trailing polymorphic slot — F-3)
// ---------------------------------------------------------------------------

// Avatar and Badge are forward-referenced here; their full types are in Node.
export type Slot =
  | {kind: 'none'}
  | {kind: 'icon'; name: string}
  | {kind: 'avatar'; node: {id: string; type: 'Avatar'; imageBinding?: ImageBinding; fallbackText?: string; size?: string; accessibilityLabel?: string}}
  | {kind: 'badge'; node: {id: string; type: 'Badge'; label: string; tone?: Tone; accessibilityLabel?: string}}
`

// Node type — recursive, hand-declared per ADR-0005 §E.
// Children types are Node[] for container components.
const NODE_TYPE = `
// ---------------------------------------------------------------------------
// § Node — recursive type alias (hand-declared: z.infer cannot resolve recursion)
// ---------------------------------------------------------------------------

export type Node =
  // Layout tier
  | {id: string; type: 'Screen'; padding?: string; safeArea?: 'top' | 'bottom' | 'both' | 'none'; children: Node[]; accessibilityLabel?: string}
  | {id: string; type: 'Section'; title?: string; caption?: string; padding?: string; children: Node[]; accessibilityLabel?: string}
  | {id: string; type: 'Stack'; gap?: string; align?: 'start' | 'center' | 'end' | 'stretch'; children: Node[]; accessibilityLabel?: string}
  | {id: string; type: 'Row'; gap?: string; align?: 'start' | 'center' | 'end'; justify?: 'start' | 'center' | 'end' | 'space-between' | 'space-around'; wrap?: boolean; children: Node[]; accessibilityLabel?: string}
  | {id: string; type: 'Card'; elevation?: 'flat' | 'raised' | 'floating'; padding?: string; radius?: string; children: Node[]; accessibilityLabel?: string}
  // Typography tier
  | {id: string; type: 'Heading'; text: string; level?: 1 | 2 | 3; align?: 'start' | 'center' | 'end'; role?: string; accessibilityLabel?: string}
  | {id: string; type: 'Body'; text: string; role?: string; color?: ColorToken; align?: 'start' | 'center' | 'end'; accessibilityLabel?: string}
  | {id: string; type: 'Caption'; text: string; color?: ColorToken; align?: 'start' | 'center' | 'end'; accessibilityLabel?: string}
  // Inputs tier
  | {id: string; type: 'TextField'; label: string; placeholder?: string; valueBinding: StringBinding; multiline?: boolean; keyboardType?: 'default' | 'email-address' | 'url'; maxLength?: number; optional?: boolean; accessibilityLabel?: string}
  | {id: string; type: 'NumberField'; label: string; placeholder?: string; valueBinding: NumberBinding; min?: number; max?: number; step?: number; optional?: boolean; accessibilityLabel?: string}
  | {id: string; type: 'DateField'; label: string; valueBinding: DateBinding; mode?: 'date' | 'time' | 'datetime'; optional?: boolean; accessibilityLabel?: string}
  | {id: string; type: 'Picker'; label: string; valueBinding: StringBinding; options: string[]; optional?: boolean; accessibilityLabel?: string}
  | {id: string; type: 'Switch'; label: string; valueBinding: BooleanBinding; accessibilityLabel?: string}
  // Display tier
  | {id: string; type: 'Stat'; label: string; valueBinding: StringBinding | NumberBinding; unit?: string; trend?: 'up' | 'down' | 'neutral'; accessibilityLabel?: string}
  | {id: string; type: 'Badge'; label: string; tone?: Tone; accessibilityLabel?: string}
  | {id: string; type: 'Chip'; label: string; action?: Action; selected?: BooleanBinding; accessibilityLabel?: string}
  | {id: string; type: 'Avatar'; imageBinding?: ImageBinding; fallbackText?: string; size?: string; accessibilityLabel?: string}
  // Lists tier
  | {id: string; type: 'List'; collectionId: string; itemTemplate: Node; emptyState?: Node; accessibilityLabel?: string}
  | {id: string; type: 'ListItem'; leading?: Slot; title: StringBinding; subtitle?: StringBinding; trailing?: Slot; tapAction?: Action; accessibilityLabel?: string}
  | {id: string; type: 'SwipeableRow'; leading?: Slot; trailing?: Slot; child: Node; accessibilityLabel?: string}
  | {id: string; type: 'EmptyState'; title: string; subtitle?: string; action?: Action; accessibilityLabel?: string}
  | {id: string; type: 'LoadingState'; message?: string; accessibilityLabel?: string}
  // Compound tier
  | {id: string; type: 'ConditionalSection'; collectionId: string; showWhen: 'whenEmpty' | 'whenNotEmpty'; children: Node[]; accessibilityLabel?: string}
  | {id: string; type: 'ListSummary'; collectionId: string; field: string; aggregation: 'count' | 'sum' | 'avg' | 'min' | 'max'; label?: string; accessibilityLabel?: string}
  | {id: string; type: 'MediaTray'; collectionId: string; imageField: string; tapAction?: Action; accessibilityLabel?: string}
  | {id: string; type: 'ImagePicker'; label: string; valueBinding: ImageBinding; optional?: boolean; accessibilityLabel?: string}
  // Actions tier
  | {id: string; type: 'Button'; label: string; action: Action; variant?: 'primary' | 'secondary' | 'destructive'; disabled?: BooleanBinding; accessibilityLabel?: string}
  | {id: string; type: 'Fab'; icon: string; action: Action; accessibilityLabel?: string}
`

// Top-level Spec and Screen types
const SPEC_TYPES = `
// ---------------------------------------------------------------------------
// § Spec and Screen types
// ---------------------------------------------------------------------------

export type SpecScreen = {
  id: string
  title?: string
  root: Node
}

export type Spec = {
  version: 1
  archetype: Archetype
  stance: Stance
  palette: Palette
  coverIcon: string
  navigation: NavPattern
  screens: SpecScreen[]
  initialScreenId: string
  collections: Collection[]
  initialState?: Record<string, BindingValue>
}
`

const content =
  HEADER +
  ENUM_TYPES +
  BINDING_TYPES +
  ACTION_TYPES +
  COLLECTION_TYPES +
  SLOT_TYPES +
  NODE_TYPE +
  SPEC_TYPES

fs.writeFileSync(OUTPUT_PATH, content, 'utf8')
process.stdout.write(`[gen-types] wrote ${OUTPUT_PATH}\n`)
